### ISSUE TITLE
add operations on Tree

### ISSUE THREAD

**Issue by Humaira-Sadia** [devnest-coders/dsa-practice#42]
add various operations on tree and some leetcode problems.

**Comment by ANKIT9761** [comment]
Can you plz describe the issue properly?

**Comment by Humaira-Sadia** [comment]
hello good afternoon sir , here in your code I want to contribute Tree
Programming DSA in java code , can you please assign this task to me..

**Comment by ANKIT9761** [comment]
Closing this
